- hosts: all
  gather_facts: no
  name: a simple localhost ping just to check wether host is available or not
  tasks:
    - name: ping
      delegate_to: localhost
      command: ping -c 2 "{{ inventory_hostname }}"
      # Because it is an reporting task
      changed_when: false 
      check_mode: false
      failed_when: router_ping.rc > 0 # will result into success for rc 0 and rc 2
      register: router_ping
